//! BRC-38/BRC-39 portable export/import integration tests.
//!
//! The fixtures under `tests/fixtures/portable/` were produced by the
//! TypeScript implementation (`wallet-toolbox/test/storage/
//! portable-fixture-gen.test.ts`) over a real seeded SQLite wallet, so these
//! tests assert genuine TS -> Rust interoperability, not a Rust-only round
//! trip. Byte-level crypto parity (including the Rust -> TS encryption
//! direction) is covered by the unit tests in `src/storage/portable/brc39.rs`.

#![cfg(feature = "sqlite")]

use serde_json::Value;

use bsv_wallet_toolbox::storage::portable::{
    canonical::canonicalize, export_brc38_json, import_brc38, import_brc39, parse_brc38_json,
    Brc38ImportOptions, ImportMode,
};
use bsv_wallet_toolbox::storage::sqlx_impl::SqliteStorage;
use bsv_wallet_toolbox::storage::traits::provider::StorageProvider;
use bsv_wallet_toolbox::storage::traits::reader::StorageReader;
use bsv_wallet_toolbox::storage::traits::reader_writer::StorageReaderWriter;
use bsv_wallet_toolbox::storage::{find_args::*, StorageConfig};
use bsv_wallet_toolbox::types::Chain;

const PASSWORD_NFC: &str = "Caf\u{e9} fixture pw";

fn fixture_string(name: &str) -> String {
    std::fs::read_to_string(format!(
        "{}/tests/fixtures/portable/{name}",
        env!("CARGO_MANIFEST_DIR")
    ))
    .expect("fixture generated by wallet-toolbox portable-fixture-gen.test.ts")
}

fn fixture_bytes(name: &str) -> Vec<u8> {
    std::fs::read(format!(
        "{}/tests/fixtures/portable/{name}",
        env!("CARGO_MANIFEST_DIR")
    ))
    .expect("fixture generated by wallet-toolbox portable-fixture-gen.test.ts")
}

fn fixture_identity_key() -> String {
    let meta: Value = serde_json::from_str(&fixture_string("meta.json")).unwrap();
    meta["identityKey"].as_str().unwrap().to_string()
}

async fn empty_storage() -> SqliteStorage {
    let config = StorageConfig {
        url: "sqlite::memory:".to_string(),
        ..Default::default()
    };
    let storage = SqliteStorage::new_sqlite(config, Chain::Test)
        .await
        .unwrap();
    storage.migrate_database().await.unwrap();
    storage.make_available().await.unwrap();
    storage
}

/// Drop the two provenTxReq fields the Rust storage schema does not model
/// (`wasBroadcast`, `rebroadcastAttempts` -- storage parity audit,
/// rust-wallet-toolbox#34). This is the single documented normalization
/// applied before byte comparison; everything else must match exactly.
fn strip_unmodeled_fields(document: &mut Value) {
    if let Some(reqs) = document["tables"]["provenTxReqs"].as_array_mut() {
        for req in reqs {
            if let Some(map) = req.as_object_mut() {
                map.remove("wasBroadcast");
                map.remove("rebroadcastAttempts");
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Canonical byte parity with the TS export
// ---------------------------------------------------------------------------

/// Parsing the TS canonical JSON and re-canonicalizing must reproduce the
/// file byte-for-byte -- this locks key ordering, number formatting, string
/// escaping, and whitespace to the TS implementation.
#[test]
fn ts_export_fixture_reparses_to_identical_bytes() {
    let json = fixture_string("brc38-ts-export.json");
    let parsed = parse_brc38_json(&json).unwrap();
    assert_eq!(canonicalize(parsed.as_value()).unwrap(), json);
}

// ---------------------------------------------------------------------------
// Restore
// ---------------------------------------------------------------------------

#[tokio::test]
async fn restore_ts_export_and_reexport_matches_byte_level() {
    let json = fixture_string("brc38-ts-export.json");
    let document = parse_brc38_json(&json).unwrap();
    let target = empty_storage().await;

    let result = import_brc38(
        &target,
        &document,
        &Brc38ImportOptions {
            mode: ImportMode::Restore,
        },
    )
    .await
    .unwrap();
    assert_eq!(result.mode, ImportMode::Restore);
    assert_eq!(result.identity_key, fixture_identity_key());
    assert_eq!(result.updates, 0);

    // Re-export from the restored target and compare the user and tables
    // sections byte-for-byte with the TS original. sourceStorage and
    // exportedAt legitimately differ (different storage, different time).
    let reexported = export_brc38_json(&target, &fixture_identity_key())
        .await
        .unwrap();
    let mut original: Value = serde_json::from_str(&json).unwrap();
    let reexported: Value = serde_json::from_str(&reexported).unwrap();
    strip_unmodeled_fields(&mut original);
    assert_eq!(
        canonicalize(&reexported["user"]).unwrap(),
        canonicalize(&original["user"]).unwrap(),
        "restored user must re-export identically"
    );
    assert_eq!(
        canonicalize(&reexported["tables"]).unwrap(),
        canonicalize(&original["tables"]).unwrap(),
        "restored tables must re-export identically (ids, timestamps, bytes)"
    );
}

#[tokio::test]
async fn restore_refuses_non_empty_target() {
    let document = parse_brc38_json(&fixture_string("brc38-ts-export.json")).unwrap();
    let target = empty_storage().await;
    let options = Brc38ImportOptions {
        mode: ImportMode::Restore,
    };
    import_brc38(&target, &document, &options).await.unwrap();
    let err = import_brc38(&target, &document, &options)
        .await
        .unwrap_err();
    assert!(
        err.to_string().contains("empty target storage"),
        "second restore must refuse: {err}"
    );
}

#[tokio::test]
async fn import_rejects_chain_mismatch() {
    let json = fixture_string("brc38-ts-export.json");
    let mut value: Value = serde_json::from_str(&json).unwrap();
    value["sourceStorage"]["chain"] = Value::String("main".to_string());
    let document = bsv_wallet_toolbox::storage::portable::validate_brc38(value).unwrap();
    let target = empty_storage().await;
    let err = import_brc38(
        &target,
        &document,
        &Brc38ImportOptions {
            mode: ImportMode::Restore,
        },
    )
    .await
    .unwrap_err();
    assert!(err.to_string().contains("chain mismatch"), "{err}");
}

// ---------------------------------------------------------------------------
// BRC-39 end-to-end
// ---------------------------------------------------------------------------

#[tokio::test]
async fn import_brc39_restores_ts_encrypted_backup() {
    let bytes = fixture_bytes("brc39-ts-default.bin");
    let target = empty_storage().await;
    let result = import_brc39(
        &target,
        &bytes,
        PASSWORD_NFC,
        &Brc38ImportOptions {
            mode: ImportMode::Restore,
        },
    )
    .await
    .unwrap();
    assert_eq!(result.identity_key, fixture_identity_key());
    assert!(result.inserts > 1);

    let user = target
        .find_user_by_identity_key(&fixture_identity_key(), None)
        .await
        .unwrap();
    assert!(user.is_some(), "restored user must exist in storage");
}

// ---------------------------------------------------------------------------
// Merge
// ---------------------------------------------------------------------------

/// Merge the TS export into a target whose autoincrement counters are offset
/// by pre-existing data, then verify id remapping end-to-end: rows land under
/// new ids, foreign keys follow them, and the imported remote sync state's
/// id-map values are rewritten through the import id-map.
#[tokio::test]
async fn merge_ts_export_remaps_ids_and_sync_maps() {
    let json = fixture_string("brc38-ts-export.json");
    let original: Value = serde_json::from_str(&json).unwrap();
    let document = parse_brc38_json(&json).unwrap();
    let target = empty_storage().await;

    // Offset the target's autoincrement ids so remapping is observable.
    let now = chrono::Utc::now().naive_utc();
    let other_user_id = target
        .insert_user(
            &bsv_wallet_toolbox::tables::User {
                created_at: now,
                updated_at: now,
                user_id: 0,
                identity_key: "02".repeat(33),
                active_storage: "elsewhere".to_string(),
            },
            None,
        )
        .await
        .unwrap();
    assert_eq!(other_user_id, 1);
    // Offset the transactions counter too, so remapped transaction ids can
    // never coincide with the source's.
    target
        .insert_transaction(
            &bsv_wallet_toolbox::tables::Transaction {
                created_at: now,
                updated_at: now,
                transaction_id: 0,
                user_id: other_user_id,
                proven_tx_id: None,
                status: bsv_wallet_toolbox::status::TransactionStatus::Unprocessed,
                reference: "offset-ref".to_string(),
                is_outgoing: false,
                satoshis: 0,
                description: "autoincrement offset".to_string(),
                version: None,
                lock_time: None,
                txid: None,
                input_beef: None,
                raw_tx: None,
            },
            None,
        )
        .await
        .unwrap();

    let result = import_brc38(
        &target,
        &document,
        &Brc38ImportOptions {
            mode: ImportMode::Merge,
        },
    )
    .await
    .unwrap();
    assert_eq!(result.mode, ImportMode::Merge);
    assert!(result.inserts > 0, "merge into empty user must insert rows");
    assert_ne!(
        result.user_id,
        original["user"]["userId"].as_i64().unwrap(),
        "target user id must differ from the source's (autoincrement offset)"
    );

    // The import-tracking sync state must map source transaction ids to the
    // new target ids.
    let source_storage_key = original["sourceStorage"]["storageIdentityKey"]
        .as_str()
        .unwrap();
    let import_state = target
        .find_sync_states(
            &FindSyncStatesArgs {
                partial: SyncStatePartial {
                    user_id: Some(result.user_id),
                    storage_identity_key: Some(source_storage_key.to_string()),
                    ..Default::default()
                },
                ..Default::default()
            },
            None,
        )
        .await
        .unwrap();
    assert_eq!(import_state.len(), 1);
    let import_map: Value = serde_json::from_str(&import_state[0].sync_map).unwrap();

    let source_tx_id = original["tables"]["transactions"][0]["transactionId"]
        .as_i64()
        .unwrap();
    let target_tx_id = import_map["transaction"]["idMap"][source_tx_id.to_string()]
        .as_i64()
        .expect("merge must record a transaction id mapping");
    let source_output = original["tables"]["outputs"]
        .as_array()
        .unwrap()
        .iter()
        .find(|o| o["transactionId"].as_i64() == Some(source_tx_id))
        .expect("fixture has an output on the first transaction");
    let target_output_id = import_map["output"]["idMap"]
        [source_output["outputId"].as_i64().unwrap().to_string()]
    .as_i64()
    .unwrap();

    // The output landed under its remapped id with its FK following the
    // transaction's remapped id.
    let outputs = target
        .find_outputs(
            &FindOutputsArgs {
                partial: OutputPartial {
                    output_id: Some(target_output_id),
                    ..Default::default()
                },
                ..Default::default()
            },
            None,
        )
        .await
        .unwrap();
    assert_eq!(outputs.len(), 1);
    assert_eq!(outputs[0].transaction_id, target_tx_id);

    // The imported remote sync state maps foreign id 777 to a source
    // transaction id and 778 to a source output id; after merge those values
    // must be rewritten through the import id-map.
    let source_remote_map: Value = original["tables"]["syncStates"]
        .as_array()
        .unwrap()
        .iter()
        .find(|s| s["storageIdentityKey"].as_str() == Some("remote-sync-storage-identity-key"))
        .expect("fixture has the remote sync state")["syncMap"]
        .clone();
    let source_777 = source_remote_map["transaction"]["idMap"]["777"]
        .as_i64()
        .unwrap();
    let source_778 = source_remote_map["output"]["idMap"]["778"]
        .as_i64()
        .unwrap();
    let expected_777 = import_map["transaction"]["idMap"][source_777.to_string()]
        .as_i64()
        .unwrap();
    let expected_778 = import_map["output"]["idMap"][source_778.to_string()]
        .as_i64()
        .unwrap();
    assert_ne!(expected_777, source_777, "offset must force real remapping");
    let remote_state = target
        .find_sync_states(
            &FindSyncStatesArgs {
                partial: SyncStatePartial {
                    user_id: Some(result.user_id),
                    storage_identity_key: Some("remote-sync-storage-identity-key".to_string()),
                    ..Default::default()
                },
                ..Default::default()
            },
            None,
        )
        .await
        .unwrap();
    assert_eq!(
        remote_state.len(),
        1,
        "imported remote sync state must exist"
    );
    let remote_map: Value = serde_json::from_str(&remote_state[0].sync_map).unwrap();
    assert_eq!(
        remote_map["transaction"]["idMap"]["777"].as_i64(),
        Some(expected_777),
        "remote sync map values must be remapped through the import id-map"
    );
    assert_eq!(
        remote_map["output"]["idMap"]["778"].as_i64(),
        Some(expected_778)
    );

    // Merging the same document again must be idempotent on inserts for
    // natural-keyed entities (rows merge, not duplicate).
    let again = import_brc38(
        &target,
        &document,
        &Brc38ImportOptions {
            mode: ImportMode::Merge,
        },
    )
    .await
    .unwrap();
    let tx_count = target
        .count_transactions(&Default::default(), None)
        .await
        .unwrap();
    assert_eq!(
        tx_count,
        original["tables"]["transactions"].as_array().unwrap().len() as i64 + 1,
        "re-merge must not duplicate transactions beyond the offset row (second run: {again:?})"
    );
}

/// A corrupt stored sync map must fail the merge, not be silently replaced
/// with an empty map: the stored id-map is the record of which source rows
/// already landed under which target ids, and overwriting it would make the
/// next round re-insert rows it should have matched.
#[tokio::test]
async fn merge_fails_loudly_on_corrupt_stored_sync_map() {
    let document = parse_brc38_json(&fixture_string("brc38-ts-export.json")).unwrap();
    let original: Value = serde_json::from_str(&fixture_string("brc38-ts-export.json")).unwrap();
    let target = empty_storage().await;

    let now = chrono::Utc::now().naive_utc();
    let user_id = target
        .insert_user(
            &bsv_wallet_toolbox::tables::User {
                created_at: now,
                updated_at: now,
                user_id: 0,
                identity_key: fixture_identity_key(),
                active_storage: "elsewhere".to_string(),
            },
            None,
        )
        .await
        .unwrap();
    let source_key = original["sourceStorage"]["storageIdentityKey"]
        .as_str()
        .unwrap();
    let source_name = original["sourceStorage"]["storageName"].as_str().unwrap();
    target
        .insert_sync_state(
            &bsv_wallet_toolbox::tables::SyncState {
                created_at: now,
                updated_at: now,
                sync_state_id: 0,
                user_id,
                storage_identity_key: source_key.to_string(),
                storage_name: source_name.to_string(),
                status: bsv_wallet_toolbox::status::SyncStatus::Unknown,
                init: false,
                ref_num: "corrupt-map-ref".to_string(),
                sync_map: "not-json{{{".to_string(),
                when: None,
                satoshis: None,
                error_local: None,
                error_other: None,
            },
            None,
        )
        .await
        .unwrap();

    let err = import_brc38(
        &target,
        &document,
        &Brc38ImportOptions {
            mode: ImportMode::Merge,
        },
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(err.contains("corrupt syncMap JSON"), "{err}");

    // The failure aborted before any overwrite: the stored (corrupt) map is
    // intact for inspection and nothing was merged.
    let states = target
        .find_sync_states(
            &FindSyncStatesArgs {
                partial: SyncStatePartial {
                    user_id: Some(user_id),
                    storage_identity_key: Some(source_key.to_string()),
                    ..Default::default()
                },
                ..Default::default()
            },
            None,
        )
        .await
        .unwrap();
    assert_eq!(states.len(), 1);
    assert_eq!(states[0].sync_map, "not-json{{{");
    assert_eq!(
        target
            .count_transactions(&Default::default(), None)
            .await
            .unwrap(),
        0,
        "nothing may merge once the sync state is known corrupt"
    );
}

/// After a merge import, the import-tracking sync state's `when` must equal
/// the latest updated_at merged (TS EntitySyncState.processSyncChunk
/// done-handling). `when` is the `since` a later sync round resumes from;
/// left unset, the next round would re-scan from the beginning of time.
#[tokio::test]
async fn merge_sets_import_sync_state_when_to_latest_merged_updated_at() {
    let json = fixture_string("brc38-ts-export.json");
    let original: Value = serde_json::from_str(&json).unwrap();
    let document = parse_brc38_json(&json).unwrap();
    let target = empty_storage().await;

    let result = import_brc38(
        &target,
        &document,
        &Brc38ImportOptions {
            mode: ImportMode::Merge,
        },
    )
    .await
    .unwrap();

    // Expected: max updated_at over the 12 chunk entity tables (user and
    // syncStates do not travel through the entity sync maps).
    let mut expected: Option<chrono::NaiveDateTime> = None;
    for table in [
        "provenTxs",
        "provenTxReqs",
        "outputBaskets",
        "transactions",
        "commissions",
        "outputs",
        "outputTags",
        "outputTagMaps",
        "txLabels",
        "txLabelMaps",
        "certificates",
        "certificateFields",
    ] {
        for row in original["tables"][table].as_array().unwrap() {
            let at = chrono::NaiveDateTime::parse_from_str(
                row["updated_at"].as_str().unwrap().trim_end_matches('Z'),
                "%Y-%m-%dT%H:%M:%S%.f",
            )
            .unwrap();
            expected = Some(expected.map_or(at, |cur| cur.max(at)));
        }
    }
    let expected = expected.expect("fixture has entity rows");

    let import_state = target
        .find_sync_states(
            &FindSyncStatesArgs {
                partial: SyncStatePartial {
                    user_id: Some(result.user_id),
                    storage_identity_key: Some(
                        original["sourceStorage"]["storageIdentityKey"]
                            .as_str()
                            .unwrap()
                            .to_string(),
                    ),
                    ..Default::default()
                },
                ..Default::default()
            },
            None,
        )
        .await
        .unwrap();
    assert_eq!(import_state.len(), 1);
    assert_eq!(
        import_state[0].when,
        Some(expected),
        "when must record the latest updated_at this import transferred"
    );
}

/// A restore that fails mid-way must roll back completely and surface the
/// original insert error — the target must be left exactly as found
/// (restorable), never partially written.
#[tokio::test]
async fn restore_failure_rolls_back_and_surfaces_the_original_error() {
    // Two provenTxs with distinct ids but the same txid pass BRC-38
    // validation (which checks id uniqueness only) and then violate the
    // proven_txs.txid UNIQUE constraint mid-transaction.
    let mut doc = minimal_document();
    // minimal_document carries only what the validators need; decoding into
    // table structs additionally needs the full settings row.
    doc["sourceStorage"]["dbtype"] = Value::String("SQLite".to_string());
    doc["sourceStorage"]["maxOutputScript"] = Value::from(1024);
    let proven = |id: i64| {
        serde_json::json!({
            "created_at": "2026-01-02T03:04:05.006Z",
            "updated_at": "2026-01-02T03:04:05.006Z",
            "provenTxId": id,
            "txid": "duplicate-txid",
            "height": 1,
            "index": 0,
            "merklePath": "AA==",
            "rawTx": "AA==",
            "blockHash": "block-hash",
            "merkleRoot": "merkle-root"
        })
    };
    doc["tables"]["provenTxs"] = serde_json::json!([proven(1), proven(2)]);
    let poisoned = parse_brc38_json(&doc.to_string()).unwrap();
    let target = empty_storage().await;
    let options = Brc38ImportOptions {
        mode: ImportMode::Restore,
    };

    let err = import_brc38(&target, &poisoned, &options)
        .await
        .unwrap_err()
        .to_string();
    assert!(
        err.contains("UNIQUE") || err.contains("unique"),
        "the original constraint violation must surface: {err}"
    );

    // Rollback left the target fully empty...
    assert_eq!(
        target.count_users(&Default::default(), None).await.unwrap(),
        0
    );
    assert_eq!(
        target
            .count_proven_txs(&Default::default(), None)
            .await
            .unwrap(),
        0
    );
    // ...and healthy: a valid restore into the same target still succeeds.
    let good = parse_brc38_json(&fixture_string("brc38-ts-export.json")).unwrap();
    import_brc38(&target, &good, &options).await.unwrap();
}

// ---------------------------------------------------------------------------
// Validator rejections (mirroring the TS test suite)
// ---------------------------------------------------------------------------

fn minimal_document() -> Value {
    serde_json::json!({
        "brc": 38,
        "title": "User Wallet Data Format",
        "formatVersion": 1,
        "exportedAt": "2026-01-02T03:04:05.006Z",
        "sourceStorage": {
            "created_at": "2026-01-02T03:04:05.006Z",
            "updated_at": "2026-01-02T03:04:05.006Z",
            "storageIdentityKey": "source-storage",
            "storageName": "source-storage",
            "chain": "test"
        },
        "user": {
            "created_at": "2026-01-02T03:04:05.006Z",
            "updated_at": "2026-01-02T03:04:05.006Z",
            "userId": 1,
            "identityKey": "identity-key",
            "activeStorage": "source-storage"
        },
        "tables": {
            "provenTxs": [], "provenTxReqs": [], "outputBaskets": [],
            "transactions": [], "commissions": [], "outputs": [],
            "outputTags": [], "outputTagMaps": [], "txLabels": [],
            "txLabelMaps": [], "certificates": [], "certificateFields": [],
            "syncStates": []
        }
    })
}

fn expect_reject(document: Value, needle: &str) {
    let err = parse_brc38_json(&document.to_string())
        .unwrap_err()
        .to_string();
    assert!(err.contains(needle), "expected {needle:?} in: {err}");
}

#[test]
fn validators_reject_malformed_documents() {
    // Malformed JSON.
    let err = parse_brc38_json("{not-json").unwrap_err().to_string();
    assert!(err.contains("Invalid BRC-38 JSON"), "{err}");

    // Null values anywhere in the document.
    let mut doc = minimal_document();
    doc["user"]["activeStorage"] = Value::Null;
    expect_reject(doc, "must omit null values");

    // Unpadded base64 in a binary column.
    let mut doc = minimal_document();
    doc["tables"]["transactions"] = serde_json::json!([{
        "created_at": "2026-01-02T03:04:05.006Z",
        "updated_at": "2026-01-02T03:04:05.006Z",
        "transactionId": 1, "userId": 1, "inputBEEF": "abc"
    }]);
    expect_reject(doc, "padded base64");

    // JSON column that is not an object.
    let mut doc = minimal_document();
    doc["tables"]["syncStates"] = serde_json::json!([{
        "created_at": "2026-01-02T03:04:05.006Z",
        "updated_at": "2026-01-02T03:04:05.006Z",
        "syncStateId": 1, "userId": 1,
        "storageIdentityKey": "storage", "storageName": "storage",
        "syncMap": "{}"
    }]);
    expect_reject(doc, "syncMap must be an object");

    // Malformed timestamp.
    let mut doc = minimal_document();
    doc["exportedAt"] = Value::String("2026-01-02 03:04:05".to_string());
    expect_reject(doc, "UTC ISO timestamp");

    // Calendar-invalid timestamp that matches the shape.
    let mut doc = minimal_document();
    doc["exportedAt"] = Value::String("2026-02-30T03:04:05.006Z".to_string());
    expect_reject(doc, "is invalid");
}

#[test]
fn validators_reject_dangling_relationships() {
    // output.transactionId referencing nothing.
    let mut doc = minimal_document();
    doc["tables"]["outputs"] = serde_json::json!([{
        "created_at": "2026-01-02T03:04:05.006Z",
        "updated_at": "2026-01-02T03:04:05.006Z",
        "outputId": 1, "userId": 1, "transactionId": 99
    }]);
    expect_reject(doc, "output.transactionId");

    // output.spentBy referencing nothing.
    let mut doc = minimal_document();
    doc["tables"]["transactions"] = serde_json::json!([{
        "created_at": "2026-01-02T03:04:05.006Z",
        "updated_at": "2026-01-02T03:04:05.006Z",
        "transactionId": 1, "userId": 1
    }]);
    doc["tables"]["outputs"] = serde_json::json!([{
        "created_at": "2026-01-02T03:04:05.006Z",
        "updated_at": "2026-01-02T03:04:05.006Z",
        "outputId": 1, "userId": 1, "transactionId": 1, "spentBy": 99
    }]);
    expect_reject(doc, "output.spentBy");

    // provenTxReq.txid without a matching transaction.
    let mut doc = minimal_document();
    doc["tables"]["provenTxReqs"] = serde_json::json!([{
        "created_at": "2026-01-02T03:04:05.006Z",
        "updated_at": "2026-01-02T03:04:05.006Z",
        "provenTxReqId": 1, "txid": "txid-without-matching-transaction"
    }]);
    expect_reject(doc, "provenTxReq.txid");

    // userId mismatch.
    let mut doc = minimal_document();
    doc["tables"]["outputBaskets"] = serde_json::json!([{
        "created_at": "2026-01-02T03:04:05.006Z",
        "updated_at": "2026-01-02T03:04:05.006Z",
        "basketId": 1, "userId": 2, "name": "b",
        "numberOfDesiredUTXOs": 1, "minimumDesiredUTXOValue": 1, "isDeleted": false
    }]);
    expect_reject(doc, "outputBaskets.userId does not match");

    // Duplicate primary keys.
    let mut doc = minimal_document();
    doc["tables"]["txLabels"] = serde_json::json!([
        {"created_at": "2026-01-02T03:04:05.006Z", "updated_at": "2026-01-02T03:04:05.006Z",
         "txLabelId": 1, "userId": 1, "label": "a", "isDeleted": false},
        {"created_at": "2026-01-02T03:04:05.006Z", "updated_at": "2026-01-02T03:04:05.006Z",
         "txLabelId": 1, "userId": 1, "label": "b", "isDeleted": false}
    ]);
    expect_reject(doc, "duplicate txLabels.txLabelId");

    // Wrong document constants.
    let mut doc = minimal_document();
    doc["brc"] = Value::from(37);
    expect_reject(doc, "brc must equal 38");
}

// ---------------------------------------------------------------------------
// Rust -> TS artifact generation
// ---------------------------------------------------------------------------

/// Regenerate the Rust-produced interop artifacts that the TS side verifies
/// (`wallet-toolbox/test/storage/portable-rust-verify.test.ts`): restore the
/// TS fixture, then export it back out through the full Rust BRC-38 and
/// BRC-39 (default KDF, random salt/nonce) paths. Set RUST_ARTIFACT_OUT=1 to
/// rewrite `tests/fixtures/portable/{brc38,brc39}-rust-export.*`; without it
/// the test only proves the artifacts can be produced.
#[tokio::test]
async fn generate_rust_export_artifacts() {
    let document = parse_brc38_json(&fixture_string("brc38-ts-export.json")).unwrap();
    let target = empty_storage().await;
    import_brc38(
        &target,
        &document,
        &Brc38ImportOptions {
            mode: ImportMode::Restore,
        },
    )
    .await
    .unwrap();

    // One export, encrypted as-is, so the .json and .bin artifacts carry the
    // same document (including exportedAt).
    let exported =
        bsv_wallet_toolbox::storage::portable::export_brc38(&target, &fixture_identity_key())
            .await
            .unwrap();
    let json = canonicalize(exported.as_value()).unwrap();
    let brc39 = bsv_wallet_toolbox::storage::portable::encrypt_brc39(&exported, PASSWORD_NFC, None)
        .unwrap();
    assert_eq!(&brc39[..4], b"WDAT");

    if std::env::var("RUST_ARTIFACT_OUT").is_ok() {
        let dir = format!("{}/tests/fixtures/portable", env!("CARGO_MANIFEST_DIR"));
        std::fs::write(format!("{dir}/brc38-rust-export.json"), &json).unwrap();
        std::fs::write(format!("{dir}/brc39-rust-export.bin"), &brc39).unwrap();
    }
}

/// The committed Rust-produced BRC-39 artifact (already verified against TS
/// by `portable-rust-verify.test.ts`) must keep decrypting and restoring.
#[tokio::test]
async fn committed_rust_artifact_still_imports() {
    let bytes = fixture_bytes("brc39-rust-export.bin");
    let json = fixture_string("brc38-rust-export.json");
    let decrypted =
        bsv_wallet_toolbox::storage::portable::decrypt_brc39(&bytes, PASSWORD_NFC).unwrap();
    assert_eq!(canonicalize(decrypted.as_value()).unwrap(), json);

    let target = empty_storage().await;
    let result = import_brc38(
        &target,
        &decrypted,
        &Brc38ImportOptions {
            mode: ImportMode::Restore,
        },
    )
    .await
    .unwrap();
    assert_eq!(result.identity_key, fixture_identity_key());
}
