//! BRC-38/BRC-39 portable wallet data export and import.
//!
//! Ports `wallet-toolbox/src/storage/portable/index.ts` (the TS reference is the
//! specification; every function keeps its TS name in camelCase-to-snake_case form).
//!
//! - **BRC-38** is the plaintext structured format: one canonical JSON document
//!   holding a single user's complete wallet state (13 tables plus settings and
//!   user rows). Export produces canonical bytes; import validates the full
//!   relational graph before writing anything.
//! - **BRC-39** is the encrypted container: a fixed 33-byte header, Argon2id
//!   password KDF, and AES-GCM (TS SDK framing, 32-byte nonce) over the
//!   canonical BRC-38 JSON.
//!
//! This is a disaster-recovery format, not sync: whole-wallet, strict,
//! one-shot. The byte-level shape must match the TypeScript implementation
//! exactly, in both directions. The interop fixtures in
//! `tests/fixtures/portable/` are generated by the TS implementation
//! (`wallet-toolbox/test/storage/portable-fixture-gen.test.ts`) and the tests
//! assert byte equality against them.

pub mod brc39;
pub mod canonical;
pub mod export;
pub mod import;
#[cfg(feature = "sqlite")]
mod restore_sqlite;
pub mod row;
pub mod validate;

pub use brc39::{decrypt_brc39, encrypt_brc39, export_brc39, import_brc39, Brc39Options};
pub use export::{export_brc38, export_brc38_json};
pub use import::{
    import_brc38, parse_brc38_json, Brc38ImportOptions, Brc38ImportResult, ImportMode,
    PortableStorage,
};
pub use validate::{validate_brc38, Brc38WalletData};
